### ISSUE TITLE
Help Diffract find its logo!

### ISSUE THREAD

**Issue by aloisdg** [d-edge/Diffract#1]
Hello,

Help us to create a logo for Diffract or vote for one. Also any icon idea is welcome :)

Cheers,

**Comment by Tarmil** [comment]
I like your proposal a lot! Especially with the way it turns into a D.

Another concept I had in mind was the double slit experiment: it's based on diffraction, and like a diff it looks like 2 items as input and many smaller items as output. No idea how to make that look like a nice logo though 😄 

![image](https://user-images.githubusercontent.com/921395/137619874-d9b2bece-2fa8-4fad-ac16-193bf25ea1e5.png)

**Comment by MiniKeb** [comment]
@aloisdg Thanks!
In fact, i played with the @Tarmil 's image.
I kept the "equality" sign (on the first wall) that sound like "comparison" to me, that is the aim of the library.
And I loved your idea with the D form, but i've tried to keep the blur effect due to diffraction.

**Comment by aloisdg** [comment]
@Tarmil selected the first one for the project
