### ISSUE TITLE
Use icon in paket to get the icon on nuget

### ISSUE THREAD

**Issue by aloisdg** [d-edge/Diffract#10]
Hello!

The logo is currently note visible.

![image](https://user-images.githubusercontent.com/3449303/143889842-cf6f5dc6-ab2c-43f0-a02d-50c4325b8187.png)

Use icon in paket to get the icon on nuget. Note that icon is supported with NuGet 5.3.0 and above.

[source](https://docs.microsoft.com/en-us/nuget/reference/nuspec#icon)

This change is an edit of [paket.template](https://github.com/d-edge/Diffract/blob/60907f729d72af3629b3269baca6736a35508f23/src/Diffract/paket.template). We can add a line with `icon ..\diffract-64x64.png`. I think it should work.

Cheers,

**Comment by Tarmil** [comment]
Unfortunately, support for `icon` in paket.template is still a pending issue 🙁https://github.com/fsprojects/Paket/issues/3710

**Comment by aloisdg** [comment]
`iconUrl` seems to be supported. We could try that?

**Comment by aloisdg** [comment]
[example](https://github.com/fsprojects/Paket/blob/e65f8a5760fb9f7014f48d309bf537ff540bf749/tests/Paket.Tests/Packaging/TemplateFileParsing.fs) on paket
