### ISSUE TITLE
API is inconvenient to call from C#

### ISSUE THREAD

**Issue by Tarmil** [d-edge/Diffract#16]
C# seems to have odd behavior when trying to use a type whose name is the same as a namespace. Calling `Diffract.Assert` poses no issue in the project's tests: they are inside the `Diffract` namespace and therefore have the class `Diffract.Diffract` in scope. But in a real-life project, `using Diffract` doesn't work as well:

```csharp
namespace MyNamespace;

using Diffract;

Diffract.Assert(1, 2);
// Error CS0234 : The type or namespace name 'Assert' does not exist in the namespace 'Diffract' (are you missing an assembly reference?)
```

The compiler thinks we're trying to use the namespace `Diffract` when we're in fact trying to use the class `Diffract`. The solution right now is to fully qualify the call:

```csharp
Diffract.Diffract.Assert(1, 2);
```

But that's not very nice; we should fix this. It's okay to change the API, that's what version 0.x is for 😉

We have several options to remove the ambiguity:
* Nest the namespace, for example `Dedge.Diffract`.
* Change the class name. `Differ` maybe? (we can put `ModuleSuffix` on the existing F# module to avoid a duplicate definition)
* Other ideas?

**Comment by aloisdg** [comment]
`Diffract.Diffract` breaks the following rules:

> ❌ DO NOT use the same name for a namespace and a type in that namespace.

In Cardizer and Cardidy, we are using `Dedge` as namespace. I think it is working quite great for us. Note that it follows the dotnet guidelines:

> ✔️ DO prefix namespace names with a company name to prevent namespaces from different companies from having the same name.

> ✔️ DO use PascalCasing, and separate namespace components with periods (e.g., `Microsoft.Office.PowerPoint`).

The second point is followed by a note:

> If your brand employs nontraditional casing, you should follow the casing defined by your brand, even if it deviates from normal namespace casing.

Our company's name, D-EDGE, includes the invalid character '-'. In the context of a namespace, we have to ditch it. Valid choices are:

- DEDGE
- DEdge
- Dedge

or even

- D_EDGE
- D_Edge
- D_edge

To keep it simple, we ignore any ideas including non letters and choose the most common namespace casing. So that why Cardizer and Cardidy use `Dedge`.

main reading: [Names of Namespaces](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces)

**Comment by Tarmil** [comment]
As discussed a few days ago, we pretty much unanimously agreed that we should apply both proposed changes:

* Nest the namespace under a D-EDGE branding;
* Rename the main class from `Diffract` to `Differ`.

As for the specific name to use for D-EDGE branding, `DEdge` seems to be the favorite option, as it is the proper PascalCase writing of the two separate words "D" and "EDGE". It is the most likely to be properly pronounced /di:'ɛdʒ/, whereas `Dedge` or `DEDGE` run the risk of being improperly pronounced /dɛdʒ/. However if we are to use this spelling, we will want to do it consistently across all our projects. This implies breaking changes in Cardizer and Cardidy, which are currently using `Dedge` as their root namespace.

This also raises another question: should we also rename the NuGet package from `Diffract` to `DEdge.Diffract`? I believe we should.

**Comment by aloisdg** [comment]
+1 to rename Diffract to `DEdge.Diffract`.

**Comment by aloisdg** [comment]
A quick table to format @Tarmil and others people arguments:

|                                            | DEDGE | Dedge | DEdge |
|--------------------------------------------|-------|-------|-------|
| Only letter characters                     | ✔️     | ✔️     | ✔️     |
| Follow dotnet brand casing                 | ✔️     | ✔️     | ✔️     |
| Follow common Pascal casing                | ❌     | ✔️     | ✔️     |
| Most likely to be pronounce /di:'ɛdʒ/ | ❌     | ❌     | ✔️     |

**Comment by aloisdg** [comment]
Note that this decision will impact other org's projects

**Comment by aloisdg** [comment]
The double uppercase letter is quite common in dotnet withe the idiom of NFoo:
- https://nunit.org/
- http://www.n-fluent.net
