### ISSUE TITLE
Add netfx support?

### ISSUE THREAD

**Issue by thinkbeforecoding** [d-edge/Diffract#6]
It seems targeting netfx (net472/net48 or netstandard2.0) would be doable without change.
That would no exclude previous framworks from working

**Comment by aloisdg** [comment]
netstandard2.0 is the current targeted framework:

https://github.com/d-edge/Diffract/blob/be296cd35d79d76f15c71d5aa445a7392c11e94b/src/Diffract/Diffract.fsproj#L4

@thinkbeforecoding Can we close this issue?

**Comment by thinkbeforecoding** [comment]
Yes, perfect 👍
